export const SET_POSITION = 'SET POSITION';
export const SET_NAVIGATION = 'SET NAVIGATION';
export const CLEAR_NAVIGATION = 'CLEAR NAVIGATION';
export const SET_STATUS = 'SET STATUS';
export const SET_AVAILABLE_STATUS = 'SET AVAILABLE STATUS';
export const SET_INCIDENT = 'SET INCIDENT';
export const CLEAR_INCIDENT = 'CLEAR INCIDENT';

export const CREATE_INCIDENT = 'CREATE INCIDENT';
export const REMOVE_INCIDENT = 'REMOVE INCIDENT';
export const ADD_SUPPORT_UNIT = 'ADD SUPPORT UNIT';
export const REMOVE_SUPPORT_UNIT = 'REMOVE SUPPORT UNIT';
export const REMOVE_ALL_SUPPORT_UNITS = 'REMOVE ALL SUPPORT UNITS';
export const ACTIVATE_HEADQUARTER_ALARM = 'ACTIVATE HEADQUARTER ALARM';
export const DEACTIVATE_POLICEMAN_ALARM = 'DEACTIVATE POLICEMAN ALARM';
export const INCREASE_INCIDENTS_COUNTER = 'INCREASE INCIDENTS COUNTER';

export const ADD_LOG = 'ADD LOG';

export const CREATE_INCIDENT_REQUESTED = 'CREATE INCIDENT REQUESTED';
export const REMOVE_INCIDENT_REQUESTED = 'REMOVE INCIDENT REQUESTED';

export const CLEAR = 'CLEAR';

export const STEP = 'STEP';
